"""
Neural-Org Skill Catalog — 40+ production-ready skills seeded for the marketplace.
"""

SKILLS_CATALOG = [
    # ── Research & Intelligence ────────────────────────────────────────────
    {
        "id": "skill-web-researcher", "name": "Web Researcher",
        "description": "Advanced web research with source citation, fact-checking, and structured summaries. Supports real-time web access.",
        "author": "clawhub", "author_verified": True, "version": "2.3.1",
        "downloads": 14_820, "rating": 4.8, "reviews": 198,
        "category": "research", "tags": ["web", "search", "citations", "scraping"],
        "price": "free", "color": "#22d3ee", "source": "clawhub", "featured": True,
        "capabilities": ["web_search", "fact_check", "summarize"],
        "permissions": ["network"], "updated_at": "2024-11-20",
    },
    {
        "id": "skill-market-intel", "name": "Market Intelligence",
        "description": "Competitor analysis, market sizing, trend identification, and SWOT generation from web + internal data.",
        "author": "neuralops", "author_verified": True, "version": "1.8.0",
        "downloads": 8_442, "rating": 4.7, "reviews": 87,
        "category": "research", "tags": ["market", "competitive", "SWOT", "trends"],
        "price": "free", "color": "#22d3ee", "source": "clawhub", "featured": False,
        "capabilities": ["web_search", "analyze", "summarize"],
        "permissions": ["network"], "updated_at": "2024-10-15",
    },
    {
        "id": "skill-academic-research", "name": "Academic Research",
        "description": "Search ArXiv, PubMed, Semantic Scholar. Extract, summarize, and cite academic papers.",
        "author": "clawhub", "author_verified": True, "version": "1.5.2",
        "downloads": 6_100, "rating": 4.6, "reviews": 61,
        "category": "research", "tags": ["academic", "arxiv", "pubmed", "papers"],
        "price": "free", "color": "#22d3ee", "source": "clawhub", "featured": False,
        "capabilities": ["search_papers", "summarize", "cite"],
        "permissions": ["network"], "updated_at": "2024-09-08",
    },
    {
        "id": "skill-news-monitor", "name": "News Monitor",
        "description": "Real-time news tracking with sentiment analysis, topic clustering, and daily digest generation.",
        "author": "hermes-labs", "author_verified": True, "version": "3.0.0",
        "downloads": 11_200, "rating": 4.5, "reviews": 134,
        "category": "research", "tags": ["news", "sentiment", "digest", "realtime"],
        "price": "free", "color": "#22d3ee", "source": "hermeshub", "featured": True,
        "capabilities": ["news_search", "sentiment", "cluster"],
        "permissions": ["network"], "updated_at": "2024-12-01",
    },

    # ── Code Generation ────────────────────────────────────────────────────
    {
        "id": "skill-python-expert", "name": "Python Expert",
        "description": "Full-stack Python development — FastAPI, Django, data pipelines, ML scripts, testing, packaging.",
        "author": "clawhub", "author_verified": True, "version": "4.2.0",
        "downloads": 22_310, "rating": 4.9, "reviews": 312,
        "category": "coding", "tags": ["python", "fastapi", "django", "ml", "testing"],
        "price": "free", "color": "#a78bfa", "source": "clawhub", "featured": True,
        "capabilities": ["code_gen", "debug", "test_gen", "review"],
        "permissions": ["code_exec"], "updated_at": "2024-12-10",
    },
    {
        "id": "skill-react-frontend", "name": "React Frontend",
        "description": "Modern React + TypeScript development with shadcn/ui, Tailwind, Framer Motion, and testing.",
        "author": "clawhub", "author_verified": True, "version": "3.1.0",
        "downloads": 18_900, "rating": 4.8, "reviews": 245,
        "category": "coding", "tags": ["react", "typescript", "tailwind", "shadcn"],
        "price": "free", "color": "#a78bfa", "source": "clawhub", "featured": True,
        "capabilities": ["code_gen", "component_design", "test_gen"],
        "permissions": ["code_exec"], "updated_at": "2024-11-28",
    },
    {
        "id": "skill-backend-apis", "name": "Backend API Builder",
        "description": "Design and implement REST/GraphQL APIs. Express, FastAPI, Prisma, database schema generation.",
        "author": "neuralops", "author_verified": True, "version": "2.0.1",
        "downloads": 13_400, "rating": 4.7, "reviews": 178,
        "category": "coding", "tags": ["api", "rest", "graphql", "schema"],
        "price": "free", "color": "#a78bfa", "source": "clawhub", "featured": False,
        "capabilities": ["api_design", "schema_gen", "code_gen"],
        "permissions": ["code_exec"], "updated_at": "2024-10-30",
    },
    {
        "id": "skill-code-reviewer", "name": "Code Reviewer",
        "description": "Automated code review for security, performance, maintainability. OWASP checks, complexity metrics.",
        "author": "securebot", "author_verified": True, "version": "1.9.0",
        "downloads": 9_800, "rating": 4.6, "reviews": 102,
        "category": "coding", "tags": ["review", "security", "performance", "owasp"],
        "price": "free", "color": "#a78bfa", "source": "hermeshub", "featured": False,
        "capabilities": ["code_review", "security_scan", "metrics"],
        "permissions": ["code_read"], "updated_at": "2024-11-05",
    },
    {
        "id": "skill-test-generator", "name": "Test Generator",
        "description": "Auto-generate unit, integration, and E2E tests from code or specs. Jest, pytest, Playwright support.",
        "author": "clawhub", "author_verified": True, "version": "2.4.0",
        "downloads": 7_650, "rating": 4.5, "reviews": 89,
        "category": "coding", "tags": ["testing", "jest", "pytest", "playwright", "e2e"],
        "price": "free", "color": "#a78bfa", "source": "clawhub", "featured": False,
        "capabilities": ["test_gen", "coverage_analysis"],
        "permissions": ["code_exec"], "updated_at": "2024-09-22",
    },
    {
        "id": "skill-db-optimizer", "name": "Database Optimizer",
        "description": "SQL query optimization, index recommendations, schema normalization, and migration generation.",
        "author": "datacraft", "author_verified": False, "version": "1.2.0",
        "downloads": 5_200, "rating": 4.4, "reviews": 53,
        "category": "coding", "tags": ["sql", "database", "index", "optimization"],
        "price": "free", "color": "#a78bfa", "source": "github", "featured": False,
        "capabilities": ["query_optimize", "schema_review", "migration_gen"],
        "permissions": ["db_read"], "updated_at": "2024-08-14",
    },

    # ── Data Analysis ──────────────────────────────────────────────────────
    {
        "id": "skill-csv-analyst", "name": "CSV Data Analyst",
        "description": "Upload CSV files for instant statistical analysis, outlier detection, visualization code, and insight reports.",
        "author": "clawhub", "author_verified": True, "version": "3.0.0",
        "downloads": 16_700, "rating": 4.8, "reviews": 220,
        "category": "data", "tags": ["csv", "stats", "visualization", "pandas"],
        "price": "free", "color": "#10b981", "source": "clawhub", "featured": True,
        "capabilities": ["data_analysis", "stats", "visualize", "summarize"],
        "permissions": ["file_read"], "updated_at": "2024-12-05",
    },
    {
        "id": "skill-sql-assistant", "name": "SQL Assistant",
        "description": "Natural language to SQL. Query optimization, schema explanation, stored procedures, and migration scripts.",
        "author": "querycraft", "author_verified": True, "version": "2.1.0",
        "downloads": 11_300, "rating": 4.7, "reviews": 145,
        "category": "data", "tags": ["sql", "nlp", "query", "database"],
        "price": "free", "color": "#10b981", "source": "hermeshub", "featured": False,
        "capabilities": ["nl_to_sql", "explain", "optimize"],
        "permissions": ["db_read"], "updated_at": "2024-11-18",
    },
    {
        "id": "skill-stats-engine", "name": "Stats Engine",
        "description": "Advanced statistical modeling — regression, A/B testing, hypothesis testing, time series, Monte Carlo sims.",
        "author": "clawhub", "author_verified": True, "version": "1.7.0",
        "downloads": 7_890, "rating": 4.6, "reviews": 78,
        "category": "data", "tags": ["statistics", "regression", "ab-test", "monte-carlo"],
        "price": "free", "color": "#10b981", "source": "clawhub", "featured": False,
        "capabilities": ["modeling", "hypothesis_test", "simulate"],
        "permissions": ["code_exec"], "updated_at": "2024-10-01",
    },

    # ── Business Intelligence ──────────────────────────────────────────────
    {
        "id": "skill-financial-model", "name": "Financial Modeler",
        "description": "DCF models, scenario analysis, cap table management, fundraising runway calculations.",
        "author": "financeAI", "author_verified": True, "version": "2.5.0",
        "downloads": 9_100, "rating": 4.7, "reviews": 93,
        "category": "business", "tags": ["finance", "dcf", "modeling", "fundraising"],
        "price": "free", "color": "#f59e0b", "source": "clawhub", "featured": True,
        "capabilities": ["model", "forecast", "analyze"],
        "permissions": [], "updated_at": "2024-11-12",
    },
    {
        "id": "skill-forecasting", "name": "Forecasting Engine",
        "description": "Revenue prediction, demand forecasting, cohort analysis. Exportable to Google Sheets or Excel.",
        "author": "neuralops", "author_verified": True, "version": "1.8.0",
        "downloads": 6_400, "rating": 4.5, "reviews": 67,
        "category": "business", "tags": ["forecast", "revenue", "cohort", "excel"],
        "price": "free", "color": "#f59e0b", "source": "hermeshub", "featured": False,
        "capabilities": ["forecast", "cohort_analysis", "export"],
        "permissions": [], "updated_at": "2024-09-30",
    },
    {
        "id": "skill-kpi-tracker", "name": "KPI Tracker",
        "description": "Define, measure, and narrate KPIs. Automated anomaly detection and weekly summary emails.",
        "author": "metricsbot", "author_verified": False, "version": "1.3.0",
        "downloads": 4_500, "rating": 4.3, "reviews": 42,
        "category": "business", "tags": ["kpi", "metrics", "monitoring", "anomaly"],
        "price": "free", "color": "#f59e0b", "source": "github", "featured": False,
        "capabilities": ["define_kpi", "monitor", "alert", "summarize"],
        "permissions": ["network"], "updated_at": "2024-08-20",
    },

    # ── Communication ──────────────────────────────────────────────────────
    {
        "id": "skill-email-composer", "name": "Email Composer",
        "description": "Professional email drafting in any tone/length. Sales emails, apologies, announcements, newsletters.",
        "author": "clawhub", "author_verified": True, "version": "4.0.0",
        "downloads": 19_200, "rating": 4.8, "reviews": 254,
        "category": "communication", "tags": ["email", "copywriting", "sales", "tone"],
        "price": "free", "color": "#ec4899", "source": "clawhub", "featured": True,
        "capabilities": ["draft", "tone_adjust", "personalize"],
        "permissions": [], "updated_at": "2024-12-08",
    },
    {
        "id": "skill-proposal-writer", "name": "Proposal Writer",
        "description": "RFP responses, business proposals, grant applications, investor memos. Multi-section structure.",
        "author": "clawhub", "author_verified": True, "version": "2.6.0",
        "downloads": 8_700, "rating": 4.7, "reviews": 98,
        "category": "communication", "tags": ["proposal", "rfp", "grant", "investor"],
        "price": "free", "color": "#ec4899", "source": "clawhub", "featured": False,
        "capabilities": ["draft", "structure", "research"],
        "permissions": ["network"], "updated_at": "2024-10-22",
    },
    {
        "id": "skill-meeting-summarizer", "name": "Meeting Summarizer",
        "description": "Transcript analysis, action item extraction, decision logging, and automated follow-up drafts.",
        "author": "recapper", "author_verified": True, "version": "3.1.0",
        "downloads": 14_100, "rating": 4.8, "reviews": 182,
        "category": "communication", "tags": ["meetings", "transcript", "actions", "summary"],
        "price": "free", "color": "#ec4899", "source": "hermeshub", "featured": True,
        "capabilities": ["transcribe", "extract_actions", "summarize"],
        "permissions": ["file_read"], "updated_at": "2024-11-30",
    },

    # ── Security ───────────────────────────────────────────────────────────
    {
        "id": "skill-vuln-scanner", "name": "Vulnerability Scanner",
        "description": "OWASP Top 10 analysis, dependency audit, CVE lookup, and remediation guidance for code + infrastructure.",
        "author": "securebot", "author_verified": True, "version": "2.2.0",
        "downloads": 10_300, "rating": 4.7, "reviews": 112,
        "category": "security", "tags": ["owasp", "cve", "audit", "security"],
        "price": "free", "color": "#ef4444", "source": "clawhub", "featured": True,
        "capabilities": ["scan", "audit", "remediate"],
        "permissions": ["code_read", "network"], "updated_at": "2024-11-15",
    },
    {
        "id": "skill-compliance-checker", "name": "Compliance Checker",
        "description": "GDPR, SOC2, ISO27001, HIPAA compliance analysis. Gap reports and remediation roadmaps.",
        "author": "securebot", "author_verified": True, "version": "1.6.0",
        "downloads": 5_800, "rating": 4.5, "reviews": 58,
        "category": "security", "tags": ["gdpr", "soc2", "hipaa", "compliance"],
        "price": "free", "color": "#ef4444", "source": "clawhub", "featured": False,
        "capabilities": ["analyze", "gap_report", "roadmap"],
        "permissions": [], "updated_at": "2024-09-12",
    },
    {
        "id": "skill-secret-scanner", "name": "Secret Scanner",
        "description": "Detect leaked API keys, passwords, tokens in code, commits, and config files. GitHub integration ready.",
        "author": "vaultguard", "author_verified": False, "version": "1.1.0",
        "downloads": 7_200, "rating": 4.4, "reviews": 73,
        "category": "security", "tags": ["secrets", "api-keys", "leaks", "git"],
        "price": "free", "color": "#ef4444", "source": "github", "featured": False,
        "capabilities": ["scan", "report", "remediate"],
        "permissions": ["code_read", "file_read"], "updated_at": "2024-10-05",
    },

    # ── DevOps & Infrastructure ────────────────────────────────────────────
    {
        "id": "skill-cicd-builder", "name": "CI/CD Pipeline Builder",
        "description": "Generate GitHub Actions, GitLab CI, CircleCI, and Jenkins pipelines. Multi-stage, environment-aware.",
        "author": "devopsai", "author_verified": True, "version": "2.0.0",
        "downloads": 11_900, "rating": 4.7, "reviews": 134,
        "category": "devops", "tags": ["cicd", "github-actions", "jenkins", "gitlab"],
        "price": "free", "color": "#6366f1", "source": "clawhub", "featured": True,
        "capabilities": ["pipeline_gen", "config_review", "debug"],
        "permissions": [], "updated_at": "2024-11-25",
    },
    {
        "id": "skill-docker-expert", "name": "Docker Expert",
        "description": "Dockerfile optimization, multi-stage builds, docker-compose, and container security hardening.",
        "author": "containerai", "author_verified": False, "version": "1.8.0",
        "downloads": 9_400, "rating": 4.6, "reviews": 97,
        "category": "devops", "tags": ["docker", "dockerfile", "compose", "containers"],
        "price": "free", "color": "#6366f1", "source": "github", "featured": False,
        "capabilities": ["dockerfile_gen", "optimize", "security"],
        "permissions": [], "updated_at": "2024-10-18",
    },
    {
        "id": "skill-k8s-assistant", "name": "Kubernetes Assistant",
        "description": "Helm charts, K8s manifest generation, resource sizing, RBAC policies, and cluster troubleshooting.",
        "author": "devopsai", "author_verified": True, "version": "2.3.0",
        "downloads": 8_100, "rating": 4.6, "reviews": 88,
        "category": "devops", "tags": ["kubernetes", "helm", "rbac", "manifests"],
        "price": "free", "color": "#6366f1", "source": "clawhub", "featured": False,
        "capabilities": ["manifest_gen", "helm_chart", "troubleshoot"],
        "permissions": [], "updated_at": "2024-11-08",
    },
    {
        "id": "skill-monitoring-setup", "name": "Monitoring Setup",
        "description": "Grafana/Prometheus configuration, alert rule generation, SLO/SLA definition, dashboard templates.",
        "author": "observeai", "author_verified": False, "version": "1.4.0",
        "downloads": 5_600, "rating": 4.4, "reviews": 56,
        "category": "devops", "tags": ["grafana", "prometheus", "alerts", "slo"],
        "price": "free", "color": "#6366f1", "source": "github", "featured": False,
        "capabilities": ["config_gen", "alert_rules", "dashboard"],
        "permissions": [], "updated_at": "2024-08-28",
    },

    # ── Project Management ─────────────────────────────────────────────────
    {
        "id": "skill-sprint-planner", "name": "Sprint Planner",
        "description": "Agile sprint planning, story breakdown, velocity estimation, backlog grooming, and retrospective facilitation.",
        "author": "agileMind", "author_verified": True, "version": "2.1.0",
        "downloads": 7_300, "rating": 4.6, "reviews": 76,
        "category": "management", "tags": ["agile", "sprint", "backlog", "scrum"],
        "price": "free", "color": "#f97316", "source": "clawhub", "featured": False,
        "capabilities": ["plan_sprint", "estimate", "retrospect"],
        "permissions": [], "updated_at": "2024-10-28",
    },
    {
        "id": "skill-risk-assessor", "name": "Risk Assessor",
        "description": "Project risk identification, probability/impact scoring, mitigation strategies, and risk register generation.",
        "author": "riskbot", "author_verified": False, "version": "1.5.0",
        "downloads": 4_900, "rating": 4.3, "reviews": 48,
        "category": "management", "tags": ["risk", "mitigation", "register", "impact"],
        "price": "free", "color": "#f97316", "source": "hermeshub", "featured": False,
        "capabilities": ["identify_risks", "score", "mitigate"],
        "permissions": [], "updated_at": "2024-09-05",
    },
    {
        "id": "skill-roadmap-builder", "name": "Roadmap Builder",
        "description": "Product roadmap generation from requirements, quarterly OKR alignment, milestone tracking.",
        "author": "clawhub", "author_verified": True, "version": "1.9.0",
        "downloads": 6_200, "rating": 4.5, "reviews": 63,
        "category": "management", "tags": ["roadmap", "product", "okr", "milestones"],
        "price": "free", "color": "#f97316", "source": "clawhub", "featured": False,
        "capabilities": ["roadmap_gen", "okr_align", "timeline"],
        "permissions": [], "updated_at": "2024-10-14",
    },

    # ── Marketing ──────────────────────────────────────────────────────────
    {
        "id": "skill-seo-optimizer", "name": "SEO Optimizer",
        "description": "On-page SEO, technical audit, keyword research, meta tags, schema markup, and content gap analysis.",
        "author": "seobrain", "author_verified": True, "version": "3.2.0",
        "downloads": 12_500, "rating": 4.7, "reviews": 158,
        "category": "marketing", "tags": ["seo", "keywords", "technical", "schema"],
        "price": "free", "color": "#84cc16", "source": "hermeshub", "featured": True,
        "capabilities": ["audit", "keyword_research", "optimize"],
        "permissions": ["network"], "updated_at": "2024-12-03",
    },
    {
        "id": "skill-content-generator", "name": "Content Generator",
        "description": "Blog posts, LinkedIn articles, Twitter threads, product descriptions. SEO-optimized + brand-voice matching.",
        "author": "clawhub", "author_verified": True, "version": "4.1.0",
        "downloads": 20_400, "rating": 4.8, "reviews": 276,
        "category": "marketing", "tags": ["content", "blog", "social", "copywriting"],
        "price": "free", "color": "#84cc16", "source": "clawhub", "featured": True,
        "capabilities": ["draft", "seo_optimize", "tone_match"],
        "permissions": [], "updated_at": "2024-12-09",
    },
    {
        "id": "skill-ad-copy-writer", "name": "Ad Copy Writer",
        "description": "Google Ads, Meta Ads, LinkedIn Ads. A/B headline variations, CTR prediction scoring, landing page copy.",
        "author": "adcraft", "author_verified": False, "version": "1.7.0",
        "downloads": 8_900, "rating": 4.5, "reviews": 92,
        "category": "marketing", "tags": ["ads", "ppc", "copy", "ctr"],
        "price": "free", "color": "#84cc16", "source": "hermeshub", "featured": False,
        "capabilities": ["draft_ads", "ab_variants", "ctr_score"],
        "permissions": [], "updated_at": "2024-10-20",
    },

    # ── Finance ────────────────────────────────────────────────────────────
    {
        "id": "skill-budget-optimizer", "name": "Budget Optimizer",
        "description": "Cost reduction analysis, spend categorization, vendor comparison, budget reallocation recommendations.",
        "author": "financeAI", "author_verified": True, "version": "2.0.0",
        "downloads": 5_400, "rating": 4.5, "reviews": 54,
        "category": "finance", "tags": ["budget", "cost", "vendor", "savings"],
        "price": "free", "color": "#f59e0b", "source": "clawhub", "featured": False,
        "capabilities": ["analyze", "recommend", "categorize"],
        "permissions": [], "updated_at": "2024-09-28",
    },
    {
        "id": "skill-invoice-processor", "name": "Invoice Processor",
        "description": "Automated invoice data extraction, vendor categorization, approval routing, and accounting export.",
        "author": "financeAI", "author_verified": True, "version": "1.5.0",
        "downloads": 6_800, "rating": 4.6, "reviews": 70,
        "category": "finance", "tags": ["invoice", "extraction", "accounting", "automation"],
        "price": "free", "color": "#f59e0b", "source": "clawhub", "featured": False,
        "capabilities": ["extract", "categorize", "export"],
        "permissions": ["file_read"], "updated_at": "2024-10-10",
    },

    # ── Customer Support ───────────────────────────────────────────────────
    {
        "id": "skill-ticket-classifier", "name": "Ticket Classifier",
        "description": "Automatic support ticket categorization, priority scoring, routing to right team, and response templates.",
        "author": "supportAI", "author_verified": True, "version": "2.3.0",
        "downloads": 9_600, "rating": 4.6, "reviews": 105,
        "category": "support", "tags": ["tickets", "classification", "routing", "priority"],
        "price": "free", "color": "#22d3ee", "source": "hermeshub", "featured": False,
        "capabilities": ["classify", "route", "respond"],
        "permissions": [], "updated_at": "2024-11-22",
    },
    {
        "id": "skill-sentiment-analyzer", "name": "Sentiment Analyzer",
        "description": "Customer feedback analysis — NPS classification, churn prediction, emotion detection, trend surfacing.",
        "author": "clawhub", "author_verified": True, "version": "3.0.0",
        "downloads": 11_800, "rating": 4.7, "reviews": 132,
        "category": "support", "tags": ["sentiment", "nps", "churn", "feedback"],
        "price": "free", "color": "#22d3ee", "source": "clawhub", "featured": True,
        "capabilities": ["analyze", "classify", "predict_churn"],
        "permissions": [], "updated_at": "2024-12-02",
    },

    # ── Design & UX ────────────────────────────────────────────────────────
    {
        "id": "skill-ui-reviewer", "name": "UI Reviewer",
        "description": "Design review against 50+ UX heuristics. Nielsen Norman guidelines, accessibility check, mobile audit.",
        "author": "designbot", "author_verified": False, "version": "1.4.0",
        "downloads": 6_700, "rating": 4.4, "reviews": 68,
        "category": "design", "tags": ["ux", "accessibility", "heuristics", "mobile"],
        "price": "free", "color": "#ec4899", "source": "github", "featured": False,
        "capabilities": ["review", "accessibility", "report"],
        "permissions": [], "updated_at": "2024-09-18",
    },
    {
        "id": "skill-wireframe-gen", "name": "Wireframe Generator",
        "description": "Text-to-wireframe generation. Figma export-ready components, user flow diagrams, information architecture.",
        "author": "designbot", "author_verified": False, "version": "1.2.0",
        "downloads": 4_200, "rating": 4.3, "reviews": 41,
        "category": "design", "tags": ["wireframe", "figma", "ux", "ia"],
        "price": "free", "color": "#ec4899", "source": "github", "featured": False,
        "capabilities": ["generate", "flow_diagram", "export"],
        "permissions": [], "updated_at": "2024-08-10",
    },

    # ── Special / Premium ──────────────────────────────────────────────────
    {
        "id": "skill-autonomous-researcher", "name": "Autonomous Researcher",
        "description": "Multi-step research agent that plans, searches, synthesizes, and produces structured reports autonomously.",
        "author": "clawhub", "author_verified": True, "version": "1.0.0",
        "downloads": 3_200, "rating": 4.9, "reviews": 38,
        "category": "research", "tags": ["autonomous", "multi-step", "report", "deep-research"],
        "price": "pro", "color": "#a78bfa", "source": "clawhub", "featured": True,
        "capabilities": ["plan", "research", "synthesize", "report"],
        "permissions": ["network", "web_search"], "updated_at": "2024-12-01",
    },
    {
        "id": "skill-claude-code", "name": "Claude Code",
        "description": "Anthropic Claude with full code execution capabilities. Build, test, and debug software autonomously.",
        "author": "anthropic", "author_verified": True, "version": "1.0.0",
        "downloads": 28_400, "rating": 4.9, "reviews": 402,
        "category": "coding", "tags": ["claude", "anthropic", "code-exec", "autonomous"],
        "price": "pro", "color": "#d97706", "source": "clawhub", "featured": True,
        "capabilities": ["code_gen", "code_exec", "debug", "autonomous"],
        "permissions": ["code_exec", "file_read", "file_write"], "updated_at": "2024-12-10",
    },
    {
        "id": "skill-openai-codex", "name": "OpenAI Codex",
        "description": "GPT-4 powered coding with computer use capabilities, web browsing, and multi-file project management.",
        "author": "openai", "author_verified": True, "version": "1.0.0",
        "downloads": 24_100, "rating": 4.8, "reviews": 356,
        "category": "coding", "tags": ["openai", "codex", "computer-use", "gpt4"],
        "price": "pro", "color": "#74aa9c", "source": "clawhub", "featured": True,
        "capabilities": ["code_gen", "computer_use", "browse", "autonomous"],
        "permissions": ["code_exec", "network", "file_write"], "updated_at": "2024-12-08",
    },
    {
        "id": "skill-mcp-connector", "name": "MCP Connector",
        "description": "Connect any MCP (Model Context Protocol) server to your agents. Universal tool bridge.",
        "author": "clawhub", "author_verified": True, "version": "1.0.0",
        "downloads": 5_100, "rating": 4.7, "reviews": 52,
        "category": "devops", "tags": ["mcp", "tools", "protocol", "bridge"],
        "price": "free", "color": "#6366f1", "source": "clawhub", "featured": False,
        "capabilities": ["tool_bridge", "protocol", "extend"],
        "permissions": ["network"], "updated_at": "2024-11-28",
    },
]

SKILL_CATEGORIES = [
    {"id": "all", "label": "All Skills", "count": len(SKILLS_CATALOG)},
    {"id": "research", "label": "Research & Intel", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "research")},
    {"id": "coding", "label": "Code Generation", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "coding")},
    {"id": "data", "label": "Data Analysis", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "data")},
    {"id": "business", "label": "Business Intel", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "business")},
    {"id": "communication", "label": "Communication", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "communication")},
    {"id": "security", "label": "Security", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "security")},
    {"id": "devops", "label": "DevOps", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "devops")},
    {"id": "management", "label": "Project Mgmt", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "management")},
    {"id": "marketing", "label": "Marketing", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "marketing")},
    {"id": "finance", "label": "Finance", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "finance")},
    {"id": "support", "label": "Customer Support", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "support")},
    {"id": "design", "label": "Design & UX", "count": sum(1 for s in SKILLS_CATALOG if s["category"] == "design")},
]
